### ISSUE TITLE
Update AltDrag chocolatey package?

### ISSUE THREAD

**Issue by RamonUnch** [narnaud/chocolatey-packages#4]
I use AltDrag everywhere, I do appreciate your packages, however AltDrag is no longer maintained by its original Developer (Stefan Sundin). I thus decided to continue its development myself. It would be nice to have this up-to date version on Chocolatey...

My fork can be found here:
[https://github.com/RamonUnch/AltDrag/releases/](https://github.com/RamonUnch/AltDrag/releases/)
I am testing it on Win10 and fixed a lot of bugs already...

The decision if yours of course.

**Comment by narnaud** [comment]
@RamonUnch I'm not using AltDrag anymore, and happy to let you take ownership of the cholotey package if you want.
Just give me your chocolatey username and I can change it

**Comment by RamonUnch** [comment]
I have never created cholotey packages, but I will try whenever I will have a little more time.
As soon as I will be ready, and when I will have created a chocolatey account  I will tell you.
Thanks very much

**Comment by RamonUnch** [comment]
I have now a chocolatey username: RamonUnch
Thanks to give me the ownership of the package.

**Comment by RamonUnch** [comment]
Thanks very much, I will update the package next monday.

**Comment by narnaud** [comment]
@RamonUnch No problem, thank you for updating the package.
Please remove me as a maintainer of the package.
